### ISSUE TITLE
V: ID:46f04d9b-1559-4e5b-9385-4b84e90c7742

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/Rita#79]
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  12.9.1
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.9.1...
       Downloading and installing node 12.9.1...
       Using default npm version: 6.10.2
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       added 331 packages from 224 contributors and audited 9452 packages in 11.623s
       found 0 vulnerabilities
       
       
-----> Build
       Running build
       
       > Rita@1.1.7 build /tmp/build_724e94d2a650a3bd5878209de79f14f7
       > gulp build
       
/tmp/build_724e94d2a650a3bd5878209de79f14f7/node_modules/gulp-watch/index.js:101
		const glob;
		      ^^^^
SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/tmp/build_724e94d2a650a3bd5878209de79f14f7/gulpfile.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rita@1.1.7 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Rita@1.1.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.A5dr3/_logs/2019-09-08T15_56_54_316Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by ZyC0R3** [comment]
Build faild due to Change in Index.js in https://github.com/ZyC0R3/gulp-watch
